import './style.css';
import * as THREE from 'three';
import init, { FlightSimulator } from './wasm/flight_wasm';
import { metrics, type SimState } from './model';

const root=document.querySelector<HTMLDivElement>('#app')!;
root.innerHTML=`<header><div><strong>WASM FLIGHT LAB</strong><small>Design it. Fly it. Break it. Understand it.</small></div><nav aria-label="Primary"><button class="active">FLY</button><button>BUILD</button><button>MISSION</button><button>ANALYZE</button></nav></header><main><section id="viewport" aria-label="3D flight view"><div class="badge">LIVE · WASM 250 Hz</div><div class="help">W/S throttle · A/D roll · arrows pitch · R reset</div></section><aside><h2>FLIGHT DATA</h2><dl><dt>Aircraft</dt><dd>Beginner Quad</dd><dt>Altitude</dt><dd id="alt">—</dd><dt>Speed</dt><dd id="speed">—</dd><dt>Mass</dt><dd id="mass">—</dd><dt>Thrust / weight</dt><dd id="tw">—</dd><dt>Hover throttle</dt><dd id="hover">—</dd></dl><label>Collective <output id="throttleOut">38%</output><input id="throttle" type="range" min="0" max="100" value="38"></label><h2>PHYSICS</h2><label><input id="vectors" type="checkbox" checked> Force vectors</label><p class="note">Authoritative state is integrated in Rust/WASM at a fixed timestep. Rendering is independent.</p></aside></main><footer><span id="status">Initializing physics core…</span><button id="reset">Reset aircraft</button></footer>`;

await init(); const sim=new FlightSimulator();
const view=document.querySelector<HTMLElement>('#viewport')!;const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fb9cf);scene.fog=new THREE.Fog(0x8fb9cf,40,130);
const camera=new THREE.PerspectiveCamera(55,1,.1,500);camera.position.set(7,5,8);camera.lookAt(0,1,0);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;view.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xd9f2ff,0x37502b,2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(8,16,7);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x567847,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const runway=new THREE.Mesh(new THREE.PlaneGeometry(8,70),new THREE.MeshStandardMaterial({color:0x30363a}));runway.rotation.x=-Math.PI/2;runway.position.y=.012;scene.add(runway);for(let i=-30;i<=30;i+=6){const line=new THREE.Mesh(new THREE.PlaneGeometry(.18,3),new THREE.MeshBasicMaterial({color:0xffffff}));line.rotation.x=-Math.PI/2;line.position.set(0,.025,i);scene.add(line);}
const craft=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.5,.16,.28),new THREE.MeshStandardMaterial({color:0xf2aa3b,metalness:.25,roughness:.4}));body.castShadow=true;craft.add(body);for(const [x,z] of [[.42,.42],[.42,-.42],[-.42,.42],[-.42,-.42]]){const arm=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,Math.hypot(x,z),8),new THREE.MeshStandardMaterial({color:0x14212a}));arm.rotation.x=Math.PI/2;arm.rotation.z=Math.atan2(x,z);craft.add(arm);const rotor=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.018,24),new THREE.MeshStandardMaterial({color:0x15242c,transparent:true,opacity:.55}));rotor.position.set(x,.04,z);craft.add(rotor);}scene.add(craft);
const thrustArrow=new THREE.ArrowHelper(new THREE.Vector3(0,1,0),new THREE.Vector3(),2,0x3de3ff);scene.add(thrustArrow);
const keys=new Set<string>();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyR')sim.reset();});addEventListener('keyup',e=>keys.delete(e.code));
const slider=document.querySelector<HTMLInputElement>('#throttle')!;const output=document.querySelector<HTMLOutputElement>('#throttleOut')!;let collective=.38;slider.addEventListener('input',()=>{collective=Number(slider.value)/100;output.value=`${slider.value}%`;});document.querySelector('#reset')!.addEventListener('click',()=>sim.reset());
let accumulator=0,last=performance.now();function resize(){const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(view);resize();
function frame(now:number){const elapsed=Math.min((now-last)/1000,.05);last=now;accumulator+=elapsed;let roll=0,pitch=0;if(keys.has('KeyA'))roll=-.09;if(keys.has('KeyD'))roll=.09;if(keys.has('ArrowUp'))pitch=.09;if(keys.has('ArrowDown'))pitch=-.09;if(keys.has('KeyW'))collective=Math.min(1,collective+elapsed*.25);if(keys.has('KeyS'))collective=Math.max(0,collective-elapsed*.25);slider.value=String(Math.round(collective*100));output.value=`${slider.value}%`;
while(accumulator>=.004){sim.set_motor(0,collective+roll-pitch);sim.set_motor(1,collective-roll-pitch);sim.set_motor(2,collective-roll+pitch);sim.set_motor(3,collective+roll+pitch);sim.step(.004);accumulator-=.004;}const s=JSON.parse(sim.state_json()) as SimState;craft.position.set(s.position[1],-s.position[2],s.position[0]);craft.quaternion.set(s.attitude[1],-s.attitude[2],-s.attitude[0],s.attitude[3]);camera.position.lerp(new THREE.Vector3(craft.position.x+7,craft.position.y+4,craft.position.z+8),.025);camera.lookAt(craft.position);thrustArrow.position.copy(craft.position);thrustArrow.setLength(Math.max(.01,Math.hypot(...s.forces.thrust)/8));thrustArrow.visible=(document.querySelector<HTMLInputElement>('#vectors')!).checked;const m=metrics(s.mass);document.querySelector('#alt')!.textContent=`${(-s.position[2]).toFixed(1)} m`;document.querySelector('#speed')!.textContent=`${Math.hypot(...s.velocity).toFixed(1)} m/s`;document.querySelector('#mass')!.textContent=`${s.mass.toFixed(2)} kg`;document.querySelector('#tw')!.textContent=`${m.thrustToWeight.toFixed(2)} : 1`;document.querySelector('#hover')!.textContent=`${(m.hoverThrottle*100).toFixed(0)}% est.`;renderer.render(scene,camera);requestAnimationFrame(frame);}document.querySelector('#status')!.textContent='Simulation running locally · No server';requestAnimationFrame(frame);

